repos:    
  - repo: local    
    hooks:    
      - id: compile-java    
        name: Compile Java    
        entry: sh    
        language: system    
        always_run: true    
        pass_filenames: false    
        stages: [commit]    
        files: '\.java$'    
        args: ['-c', './Utils/compile.sh']
